# Generated by Django 5.0.6 on 2024-06-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="items/default.jpg",
                        null=True,
                        upload_to="items/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "numero_serie",
                    models.CharField(max_length=255, verbose_name="Número de Serie"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=255, verbose_name="Ubicación"),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(default=0, verbose_name="Stock Mínimo"),
                ),
                (
                    "cantidad",
                    models.IntegerField(default=0, verbose_name="Cantidad Disponible"),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Etiqueta"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(related_name="etiquetas", to="Core.item"),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="kits/default.jpg",
                        null=True,
                        upload_to="kits/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "stock_minimo",
                    models.IntegerField(default=0, verbose_name="Stock Mínimo"),
                ),
                ("items", models.ManyToManyField(related_name="kits", to="Core.item")),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="lotes/default.jpg",
                        null=True,
                        upload_to="lotes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "numero_lote",
                    models.CharField(max_length=100, verbose_name="Número de Lote"),
                ),
                (
                    "descripcion_lote",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "stock_minimo",
                    models.IntegerField(default=0, verbose_name="Stock Mínimo"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="Core.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["fecha_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento_Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Item", "Item"), ("Lote", "Lote"), ("Kit", "Kit")],
                        max_length=255,
                        verbose_name="Tipo de Artículo",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "encargado_salida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_despachados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encargado de la Salida",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_salida",
                        to="Core.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_salida",
                        to="Core.kit",
                        verbose_name="Kit",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_salida",
                        to="Core.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Salida",
                "verbose_name_plural": "Movimientos de Salida",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        max_length=255, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "etiquetas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="Core.etiqueta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento_Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Item", "Item"), ("Lote", "Lote"), ("Kit", "Kit")],
                        max_length=255,
                        verbose_name="Tipo de Artículo",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "encargado_entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_entrada",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encargado de la Entrada",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_entrada",
                        to="Core.item",
                        verbose_name="Item",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_entrada",
                        to="Core.kit",
                        verbose_name="Kit",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_entrada",
                        to="Core.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_entrada",
                        to="Core.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Entrada",
                "verbose_name_plural": "Movimientos de Entrada",
                "ordering": ["-fecha"],
            },
        ),
    ]
